version: '3'

services:
  # Laravel Application
  app:
    volumes:
      - php-socket:/var/run/php-fpm
    configs:
      - source: php_fpm_config
        target: /usr/local/etc/php-fpm.d/www.conf
    command: >
      sh -c "mkdir -p /var/run/php-fpm &&
             chown www-data:www-data /var/run/php-fpm &&
             php-fpm"

  # Nginx Service
  nginx:
    volumes:
      - php-socket:/var/run/php-fpm
    configs:
      - source: nginx_socket_config
        target: /etc/nginx/conf.d/default.conf
    depends_on:
      - app

volumes:
  php-socket:
    driver: local

configs:
  php_fpm_config:
    file: ./docker/php/fpm/www.conf
  nginx_socket_config:
    file: ./docker/nginx/socket.conf
